import React from 'react';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="bg-aurelia-bg min-h-screen pt-28 pb-20">
      <div className="max-w-3xl mx-auto px-6 space-y-8">
        <div className="space-y-2">
          <span className="text-[10px] tracking-[0.4em] uppercase text-aurelia-gold font-semibold">Legal</span>
          <h1 className="font-serif text-4xl text-aurelia-charcoal">Terms of Service</h1>
          <p className="text-xs text-aurelia-text/60 italic">Demo document — Aurelia Grand is a fictional hotel for demonstration purposes.</p>
        </div>
        <div className="space-y-4 text-sm font-light text-aurelia-text/80 leading-relaxed">
          <p>By accessing and using the Aurelia Grand website, you agree to these terms of service. This website is operated as a demonstration of an AI-powered hospitality product. No real bookings, payments, or reservations are processed.</p>
          <h3 className="font-serif text-lg text-aurelia-charcoal">Demo Mode</h3>
          <p>All pricing, availability, room details, and AI concierge responses are for demonstration purposes only. The booking flow does not process real payments. The WhatsApp integration requires a configured phone number.</p>
          <h3 className="font-serif text-lg text-aurelia-charcoal">AI Concierge Disclaimer</h3>
          <p>Aurelia is an AI digital concierge. While she is designed to be helpful and accurate, her responses are generated by an AI system. For confirmed reservations or official hotel policies, please contact a human representative.</p>
          <h3 className="font-serif text-lg text-aurelia-charcoal">Intellectual Property</h3>
          <p>All design, copy, and code presented on this site is original work created for this demonstration. Photography is sourced from Unsplash under their license terms.</p>
        </div>
        <Link href="/" className="inline-block text-xs uppercase tracking-widest text-aurelia-gold hover:underline">← Return to Hotel</Link>
      </div>
    </div>
  );
}
